spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://49.235.40.252:3306/design?useUnicode=true&characterEncoding=utf-8
    username: root
    password: tiger
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 50MB

#  http:
#    multipart:
#      enabled: true
mybatis:
  mapper-locations: classpath:com/yunduo/mapper/*Mapper.xml
